### ISSUE TITLE
DNSX module not working properly

### ISSUE THREAD

**Issue by Sicks3c** [pry0cc/axiom#482] opened 2021-10-28 13:06 UTC
## Summary

Hello Team
I noticed that dnsx is not working properly I was trying to give it a list of unresolved subs and it doesn't perform any test

## POC

* Sample of links

<img width="577" alt="Screen Shot 2021-10-28 at 13 56 00" src="https://user-images.githubusercontent.com/32225186/139259486-c25be82e-6619-4477-a5c1-102b2e7b6b08.png">

* Axiom command + output 
<img width="1415" alt="Screen Shot 2021-10-28 at 14 05 29" src="https://user-images.githubusercontent.com/32225186/139261184-b2a37e93-318c-4a28-8577-d4477c0f9042.png">

Cheers

**Comment by 0xtavian** [comment] 2021-11-03 01:49
@Sicks3c can you cd in ~/.axiom and run git pull and lmk if there are any errors? What OS are you using for your axiom-controller? I havent been able to reproduce this at all. You seem to be missing a lot of tools. I suspect you're using an old provisioner https://github.com/pry0cc/axiom/tree/master/images/provisioners and have made some local changes to .axiom causing axiom-update ( just a git pull redirecting output to /dev/null) to silently fail.

**Comment by Sicks3c** [comment] 2021-11-03 11:17
Hello @0xtavian 

I have done the git pull on ~/.axiom nothing new was pulled and I run with debug and here's the output

[debug.txt](https://github.com/pry0cc/axiom/files/7467140/debug.txt)

**Comment by 0xtavian** [comment] 2021-11-03 17:54
@Sicks3c I would follow [these steps](https://github.com/pry0cc/axiom/wiki/0-Installation#using-git-clone) to delete axiom and reinstall. I would also delete any previously saved images with axiom-images and then run axiom-configure, which will make a new image etc. 

A better approach is to provision a new cloud hosted ubuntu 20.04 machine from the cloud providers web gui, ssh into the droplet, run sudo apt dist-upgrade -y, create a user, give the user sudo privs and then run the [curl to bash installer ](https://github.com/pry0cc/axiom/wiki/0-Installation#easy-install).

Or you could just try running `axiom-build default` and showing me the output and maybe we can see whats going on, the former suggestions are more likely to work however.

**Comment by 0xtavian** [comment] 2021-11-05 03:14
@Sicks3c gong to close this issue as i am not able to reproduce. feel free to comment if u have an update

**Closed by 0xtavian** 2021-11-05 03:14 UTC
