### ISSUE TITLE
Azure provider - sudo: unable to resolve host

### ISSUE THREAD

**Issue by ResistanceIsUseless** [pry0cc/axiom#435] opened 2021-08-24 22:20 UTC
this issue doesn't break anything(that im aware of) but it should be an easy fix to add the hostname with 127.0.0.1 to /etc/hosts during build.

something like:
`hostname=$(cat /etc/hostname) && echo "127.0.0.1 $hostname" >> /etc/hosts`

**Comment by pdelteil** [comment] 2021-10-13 06:47
Hello,

How can I reproduce this error?

**Comment by 0xtavian** [comment] 2021-11-16 23:15
@ResistanceIsUseless This error seems to have come from replacing Azure's resolv.conf with [ours](https://github.com/pry0cc/axiom/blob/master/images/provisioners/default.json#L49). It seems this error, and a possible recent change to azure's ubuntu 20.04 image and cli/api, broke linux controllers using the azure provider. There is a temp patch [here](https://github.com/pry0cc/axiom/tree/azure).

**Comment by pdelteil** [comment] 2021-11-30 19:14
So, what you need to do is: 
- Remove all instances (`axiom-rm '\*' -f`)
- Switch to azure branch (`git checkout azure`) 
- Rebuild axiom (`axiom-build`) 
- Start new fleet (`axiom-fleet NAME -i 10`)
- Select instances (`axiom-select *`)

That's all!

**Comment by 0xtavian** [comment] 2021-11-30 19:33
> So, what you need to do is:
> 
> * Remove all instances (`axiom-rm '\*' -f`)
> * Switch to azure branch (`git checkout azure`)
> * Rebuild axiom (`axiom-build`)
> * Start new fleet (`axiom-fleet NAME -i 10`)
> * Select instances (`axiom-select *`)
> 
> That's all!

Correct. I hope to fix this in master sometime over the weekend. Also you can run `axiom-fleet -i 10` now, axiom will pick a random fleet prefix.

**Comment by pdelteil** [comment] 2021-11-30 19:36
Yes, I don't like the fleet prefixes because I re use scripts with the same fleet name. :D

**Comment by 0xtavian** [comment] 2022-02-07 19:23
@ResistanceIsUseless @pdelteil I pushed the fix to master yesterday. To update run `axiom-update` on the master branch and then run `axiom-build`. Im going to close this issue but lmk if you run into any problems.

**Comment by ResistanceIsUseless** [comment] 2022-02-07 21:07
I'll test and let you know if I see any issues. Thanks!

**Comment by 0xtavian** [comment] 2022-02-07 22:31
My finger slipped, ever so slightly, and I accidentally re-open the issue

**Closed by 0xtavian** 2022-02-07 22:31 UTC
Labels: Priority: High
