### ISSUE TITLE
No final result output file on FFUF modul scan

### ISSUE THREAD

**Issue by ptrk01** [pry0cc/axiom#374] opened 2021-06-26 16:27 UTC
I set up Axiom today and tried to do some test scans using standard scan modules ffuf.json and ffuf_base.json. Both modules run without any problems. The only problem is that the final output csv file is empty even though there are findings I see in the terminal output.

I run my fleet named "test" (10 instances) with the following commands: 
```
axiom-fleet test -i=10
axiom-scan urls.txt -m ffuf_base -o ffuf-output.csv
```

After the scan is done, terminal prints the following:
```
zsh:1: no matches found: test09:/home/op/scan/ffuf_base+1624720626/output/*
zsh:1: no matches found: test01:/home/op/scan/ffuf_base+1624720626/output/*
zsh:1: no matches found: test07:/home/op/scan/ffuf_base+1624720626/output/*
zsh:1: no matches found: test08:/home/op/scan/ffuf_base+1624720626/output/*
zsh:1: no matches found: test03:/home/op/scan/ffuf_base+1624720626/output/*
zsh:1: no matches found: test05:/home/op/scan/ffuf_base+1624720626/output/*
zsh:1: no matches found: test02:/home/op/scan/ffuf_base+1624720626/output/*
zsh:1: no matches found: test06:/home/op/scan/ffuf_base+1624720626/output/*
Generated 10 commands in total
Repeat set to 1
zsh:1: no matches found: test04:/home/op/scan/ffuf_base+1624720626/output/*
zsh:1: no matches found: test10:/home/op/scan/ffuf_base+1624720626/output/*
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 482.14it/s]
Mode set to CSV, merging...
Module [ ffuf_base  ] | Time: [ 00h:08m:33s ] | Input: [ 20 targets ]
```
However, the file ffuf-output.csv is empty. Did I do something wrong or is the problem somewhere else?

Thanks for your help in advance!

**Comment by 0xtavian** [comment] 2021-06-30 19:03
@ptrk01 can you show me the findings displayed to the terminal? I havent been able to recreate. Those error messages ` no matches found` seem to indicate there arent any results.

**Comment by 0xtavian** [comment] 2021-07-05 19:46
closing, unable to reproduce. feel free to reopen if you think it was a mistake to close

**Closed by 0xtavian** 2021-07-05 19:46 UTC
