### ISSUE TITLE
./axiom-exec not sending command file to fleet

### ISSUE THREAD

**Issue by cycoslave** [pry0cc/axiom#587] opened 2022-08-14 23:48 UTC
when I try to execute a command, I always get this.

bash: /tmp/exec/axiom-exec+1660520679/command: No such file or directory
bash: /tmp/exec/axiom-exec+1660520679/command: No such file or directory
bash: /tmp/exec/axiom-exec+1660520679/command: No such file or directory

After inspection, I found that the /tmp/exec/axiom-exec+1660520679/command did not get exported to the fleet
The file does exist locally at ~/.axiom/tmp/exec/axiom-exec+1660520679/command

edit: with the --quick argument it actually works.

**Comment by 0xtavian** [comment] 2022-08-22 18:37
@cycoslave can you show me the command you are running? I'm not able to reproduce this. 

```
➜  .axiom git:(master) ✗ axiom-fleet  
Initializing new fleet 'max' with 3 instances...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
Instances: [ max01 max02 max03  ]
Initialized instance 'max02' at '<redacted>'!
Initialized instance 'max01' at '<redacted>'!                                                                                                                                                                                         
Initialized instance 'max03' at '<redacted>'!                                                                                                                                                                                           
Selected: [ max01 max02 max03 ]alization...                                                                                                                                                                                                
Fleet started succesfully!
To delete your fleet, just run 'axiom-rm "max*" -f'             
                                                                                                                                                                           
➜  .axiom git:(master) ✗ axiom-exec id
=====================================================
Interlace v1.9.6        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
  0%|                                                                                                                                                                                                                | 0/3 [00:00<?, ?it/s][18:35:59] [THREAD] [ssh -F /root/.axiom/tmp/exec/axiom-exec+1661193352/sshconfig -o StrictHostKeyChecking=no -o PasswordAuthentication=no max01 'tmux new -d -s axiom-exec+1661193352 && tmux send-keys -t axiom-exec+1661193352 "bash -i /tmp/exec/axiom-exec+1661193352/command  > >(tee -a /tmp/exec/axiom-exec+1661193352/stdout.log) 2> >(tee -a /tmp/exec/axiom-exec+1661193352/stderr.log >&2) ; touch /tmp/exec/axiom-exec+1661193352/max01" ENTER ' "&& tmux send-keys -t axiom-exec+1661193352 exit ENTER"] Added to Queue 
[18:35:59] [THREAD] [ssh -F /root/.axiom/tmp/exec/axiom-exec+1661193352/sshconfig -o StrictHostKeyChecking=no -o PasswordAuthentication=no max02 'tmux new -d -s axiom-exec+1661193352 && tmux send-keys -t axiom-exec+1661193352 "bash -i /tmp/exec/axiom-exec+1661193352/command  > >(tee -a /tmp/exec/axiom-exec+1661193352/stdout.log) 2> >(tee -a /tmp/exec/axiom-exec+1661193352/stderr.log >&2) ; touch /tmp/exec/axiom-exec+1661193352/max02" ENTER ' "&& tmux send-keys -t axiom-exec+1661193352 exit ENTER"] Added to Queue 
[18:35:59] [THREAD] [ssh -F /root/.axiom/tmp/exec/axiom-exec+1661193352/sshconfig -o StrictHostKeyChecking=no -o PasswordAuthentication=no max03 'tmux new -d -s axiom-exec+1661193352 && tmux send-keys -t axiom-exec+1661193352 "bash -i /tmp/exec/axiom-exec+1661193352/command  > >(tee -a /tmp/exec/axiom-exec+1661193352/stdout.log) 2> >(tee -a /tmp/exec/axiom-exec+1661193352/stderr.log >&2) ; touch /tmp/exec/axiom-exec+1661193352/max03" ENTER ' "&& tmux send-keys -t axiom-exec+1661193352 exit ENTER"] Added to Queue 
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 32.23it/s]
uid=1000(op) gid=1000(op) groups=1000(op),27(sudo),998(docker)
uid=1000(op) gid=1000(op) groups=1000(op),27(sudo),998(docker)
uid=1000(op) gid=1000(op) groups=1000(op),27(sudo),998(docker)

```

**Comment by 0xtavian** [comment] 2022-08-28 00:55
not able to reproduce, closing. lmk if the issue continues to happen and we'll troubleshoot in the 0x00sec discord

**Closed by 0xtavian** 2022-08-28 00:55 UTC
