### ISSUE TITLE
You know computerz count from 0, right? n00b!

### ISSUE THREAD

**Issue by int0x33** [pry0cc/axiom#170] opened 2021-01-14 17:15 UTC
I ask for 3, I get 4 u n00b!
```n00b@n00bz:~# axiom-fleet -i=3
Initializing new fleet 'noyce' with 3 instances...
INITIALIZING IN 3 SECONDS, CTRL+C to quit...
Initializing noyce01 for 1 hours... This instance will cost: $0
Initializing noyce02 for 1 hours... This instance will cost: $0
Initializing noyce03 for 1 hours... This instance will cost: $0
Initializing noyce04 for 1 hours... This instance will cost: $0
>> T-Minus 180 to fleet noyce initialization...```

**Comment by pry0cc** [comment] 2021-01-14 18:29
It's noted - there's been a lot of fuckery with the initialization piece, it needs help, thank you for stoking the fires to get this fixed, I'll fix it whenever I'm not snowed over.

**Comment by int0x33** [comment] 2021-01-14 18:36
I forked and will try to take a look, was just kidding with the n00b! since you have it in axiom just rolling on with the trend :)

What about moving away from bash scripts, or you want to keep it simple? Would you accept pulls where whole scripts are replaced with say rust bins?

**Comment by pry0cc** [comment] 2021-01-14 19:56
I know what the problem is - in version < 1 we're keeping it Bash, but moving to something like Python or Go in the future is on the table. 

I have probably 3-4 more commits that I haven't fully tested yet and just need to push them. I will get to it :)

**Comment by pry0cc** [comment] 2021-01-16 16:58
https://github.com/pry0cc/axiom/commit/2baafb360d85915261bb7af360d952f293d98c46

Yeeeet

**Closed by pry0cc** 2021-01-16 16:58 UTC
