### ISSUE TITLE
support to increase your snapshot image size to 18GB

### ISSUE THREAD

**Issue by 0xAkashsec** [pry0cc/axiom#350] opened 2021-06-01 09:19 UTC
![image](https://user-images.githubusercontent.com/46501627/120299264-ad454300-c2ec-11eb-9326-c54343f62152.png)
![image](https://user-images.githubusercontent.com/46501627/120299348-be8e4f80-c2ec-11eb-8ac8-650c248544bd.png)

**Comment by mchoji** [comment] 2021-06-02 13:03
@0xAkashsec I have submitted a PR that fixes this issue. In the meanwhile, you can run the command manually 

```bash
linode-cli tickets create --description 'Hello! I have recently installed the axiom framework http://github.com/pry0cc/axiom and would like to request an image increase to 18GB please for the purposes of running packer. Thank you have a great day! - This request was automatically generated by Axiom' --summary 'Image increase request to 18GB for Axiom' --region ''
```

Remember to run `axiom-build` once your ticket gets resolved.

**Comment by 0xtavian** [comment] 2021-06-02 18:08
thanks @mchoji! Im going to close this but feel free to re-open if the issue is not resolved

**Closed by 0xtavian** 2021-06-02 18:08 UTC
